### PR TITLE
70 add footer

### LINKED ISSUE #70: add footer

### PR DESCRIPTION
**Pull request by Jehad91**
Relates #70 
close #70 
image

### CODE REVIEW

**Review by AhmedQeshta — APPROVED** [review]

**Comment by AhmedQeshta** [comment]
Solve conflicts

**Comment by Jehad91** [comment]
> Solve conflicts

I solved it in fix responseve pull request

**Review by mo7amedehab97 — CHANGES_REQUESTED** [review]
solve conflict

**Comment by Jehad91** [comment]
> 

Automatic solve when i merged the previous pull request

**Pull request merged**
